{{- if and .Values.collector.enabled (eq .Values.collector.mode "deployment") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}-collector
  labels:
    {{- include "cluster-info-collector.collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.collector.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-info-collector.collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-info-collector.collector.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cluster-info-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: collector
        image: {{ include "cluster-info-collector.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ include "cluster-info-collector.fullname" . }}-config
        - secretRef:
            name: {{ include "cluster-info-collector.fullname" . }}-secret
        resources:
          {{- toYaml .Values.collector.resources | nindent 10 }}
        {{- if .Values.config.metrics.enabled }}
        ports:
        - name: metrics
          containerPort: {{ .Values.config.metrics.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 5
        {{- end }}
      {{- with .Values.collector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.collector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.collector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
