{{- if .Values.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}-consumer
  labels:
    {{- include "cluster-info-collector.consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-info-collector.consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-info-collector.consumer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cluster-info-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: consumer
        image: {{ include "cluster-info-collector.consumerImage" . }}
        imagePullPolicy: {{ .Values.consumerImage.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ include "cluster-info-collector.fullname" . }}-config
        - secretRef:
            name: {{ include "cluster-info-collector.fullname" . }}-secret
        resources:
          {{- toYaml .Values.consumer.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep '[c]onsumer' || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep '[c]onsumer' || exit 1"
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- with .Values.consumer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.consumer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.consumer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
