{{- if .Values.consumer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}-consumer
  labels:
    {{- include "cluster-info-collector.consumer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cluster-info-collector.fullname" . }}-consumer
  minReplicas: {{ .Values.consumer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.consumer.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.consumer.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.consumer.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
