{{- if .Values.kafkaUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}-kafka-ui
  labels:
    {{- include "cluster-info-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
spec:
  type: {{ .Values.kafkaUI.service.type }}
  ports:
    - port: {{ .Values.kafkaUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cluster-info-collector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
{{- end }}
