{{- if .Values.kafkaUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}-kafka-ui
  labels:
    {{- include "cluster-info-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cluster-info-collector.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka-ui
  template:
    metadata:
      labels:
        {{- include "cluster-info-collector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kafka-ui
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.kafkaUI.securityContext | nindent 8 }}
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaUI.image.registry }}/{{ .Values.kafkaUI.image.repository }}:{{ .Values.kafkaUI.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaUI.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            {{- if .Values.kafka.enabled }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ include "cluster-info-collector.fullname" . }}-kafka:9092"
            {{- else }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ .Values.externalKafka.brokers }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.kafkaUI.resources | nindent 12 }}
      {{- with .Values.kafkaUI.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaUI.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaUI.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
