{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}
  labels:
    {{- include "cluster-info-collector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: 
    - nodes
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumes
    - persistentvolumeclaims
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources:
    - nodes
    - pods
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}
  labels:
    {{- include "cluster-info-collector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-info-collector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-info-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
