apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}-secret
  labels:
    {{- include "cluster-info-collector.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if .Values.externalPostgresql.password }}
  DB_PASSWORD: {{ .Values.externalPostgresql.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.kafka.enabled .Values.kafka.auth.enabled }}
  KAFKA_USERNAME: {{ .Values.kafka.auth.username | b64enc | quote }}
  KAFKA_PASSWORD: {{ .Values.kafka.auth.password | b64enc | quote }}
  {{- else if and (not .Values.kafka.enabled) .Values.externalKafka.auth.enabled }}
  KAFKA_USERNAME: {{ .Values.externalKafka.auth.username | b64enc | quote }}
  KAFKA_PASSWORD: {{ .Values.externalKafka.auth.password | b64enc | quote }}
  {{- end }}
