{{- if or .Values.config.metrics.enabled .Values.config.api.enabled .Values.config.streaming.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-info-collector.fullname" . }}
  labels:
    {{- include "cluster-info-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.config.metrics.enabled }}
  - port: {{ .Values.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
  {{- if .Values.config.api.enabled }}
  - port: {{ .Values.service.ports.api }}
    targetPort: api
    protocol: TCP
    name: api
  {{- end }}
  {{- if .Values.config.streaming.enabled }}
  - port: {{ .Values.service.ports.streaming }}
    targetPort: streaming
    protocol: TCP
    name: streaming
  {{- end }}
  selector:
    {{- include "cluster-info-collector.collector.selectorLabels" . | nindent 4 }}
{{- end }}
