apiVersion: v2
name: cluster-info-collector
description: A Helm chart for Kubernetes Cluster Info Collector with KRaft Kafka integration, Kafka UI monitoring, and external service support

# Chart version
version: 0.3.0

# App version
appVersion: "2.0.0"

type: application

keywords:
  - kubernetes
  - monitoring
  - cluster-info
  - kafka
  - kafka-ui
  - postgresql
  - kraft

home: https://github.com/your-org/k8s-cluster-info-collector
sources:
  - https://github.com/your-org/k8s-cluster-info-collector

maintainers:
  - name: Your Name
    email: your.email@example.com

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: kafka
    version: "26.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
